/**
 * This file is generated by the WebSocketHandler class.
 * Do not modify this file directly.
 */

export type ApiEndpoints = 	"installedInstances" |
	"getSettings" |
	"webRequest" |
	"instanceGetBackups" |
	"instanceDeleteBackup" |
	"storage.put" |
	"installInstance" |
	"fileHash" |
	"updateInstance" |
	"profiles.refresh" |
	"pinInstance" |
	"pong" |
	"ping" |
	"instanceBrowse" |
	"moveInstances" |
	"instanceRestoreBackup" |
	"instanceInstallMod" |
	"profiles.setActiveProfile" |
	"instanceOverrideModLoader" |
	"messageClient" |
	"instanceConfigure" |
	"instanceMods" |
	"profiles.is-valid" |
	"cancelInstallInstance" |
	"duplicateInstance" |
	"saveSettings" |
	"storage.get-all" |
	"uploadLogs" |
	"profiles.ms.authenticate" |
	"accounts.sign-out" |
	"openDebugTools" |
	"getInstanceFolders" |
	"instanceVersionInfo" |
	"instance.kill" |
	"launchInstance" |
	"instanceModToggle" |
	"storage.get" |
	"appInit" |
	"accounts.get-oauth" |
	"videoCache" |
	"getJavas" |
	"profiles.remove" |
	"accounts.store-oauth" |
	"modalCallback" |
	"setInstanceArt" |
	"uninstallInstance" |
	"profiles.get";