name: Bug Report
description: Report an issue with the Windows version of the FTB App
labels: [bug]
body:
  - type: dropdown
    id: os
    validations:
        required: true
    attributes:
      label: What Operating System
      multiple: false
      options:
        - Windows 11
        - Windows 10
        - Windows 8.1
        - Windows 7
        - Windows Insider Preview
        - Windows Other
        - MacOS (Latest)
        - MacOS (Beta)
        - MacOS (Old)
        - Linux (Debian)
        - Linux (Arch)
        - Linux (Other)
  - type: input
    id: debugcode
    attributes:
      label: Debug Code
      description: |
        Please click the upload logs button located in the FTB App > settings > app tab

        (ONLY IF YOUR APP WONT OPEN)
        If your app wont open please run the following tool and provide the code given 
        [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
        [Windows (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe) [MacOS (Arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64) [Linux (arm)](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
      placeholder: FTB-DBGTEVOISQIRA
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: input
    id: expectedBehaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
