variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  tags:
    - shell
  only:
    - branches
  except:
    - tags
    - /^no-ci/.*$/
  stage: build
  script:
    - cd /Users/aaronmills
    - 'export VERSION_OVERRIDE=`curl -s --header "PRIVATE-TOKEN: $WHY_GITLAB_WHY " "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages?order_by=version&sort=desc" | jq -r "first(.[] | select(.pipeline.ref == \"$CI_COMMIT_BRANCH\")).version"`'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -o public/version.json $CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven/net/creeperhost/creeperlauncher/$VERSION/creeperlauncher-$VERSION.json'
    - mkdir subprocess/build/lib
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -o subprocess/build/lib/launcher-$VERSION-all.jar $CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/maven/net/creeperhost/creeperlauncher/$VERSION/creeperlauncher-$VERSION-all.jar'
    - ./runBuild.sh
