on:
  issue_comment:
    types: [created]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job for toggling label
    steps:
      - name: Toggle label
        uses: FTBTeam/awaiting-reply-action@main
        with:
          label: "awaiting response"
          ignore-labels: ""
          remove-labels: "state: Stale"
          ignore-string: "!skip"