name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
      
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue / Pull request has been closed as there has been no recent activity after being marked as stale.'
          days-before-stale: 7
          days-before-close: 3
          days-before-pr-close: -1
          stale-issue-label: "status: stale"
          exempt-issue-labels: "status: confirmed, status: investigate, feature:request,fixed/release,fixed/dev,status: planned,question/discussion,priority/high,priority/medium,priority/low"
          exempt-all-assignees: true
          exempt-all-milestones: true
