name: Test Backend

on:
  push:
    branches:
      - main
    paths:
    - 'subprocess/**'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
jobs:      
  test-subprocess:
    name: Test Subprocess
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build subprocess
        env:
          SUBPROCESS_SENTRY_DSN: ${{ secrets.SUBPROCESS_SENTRY_DSN }}
          GITHUB_BRANCH: "test"
          CI: true
        run: |
          cd subprocess
          ./gradlew clean test -si
      # Upload the report regardless of a failure
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.os }}
          path: subprocess/build/reports/tests/
